name: build PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Set up CI environment
        run: .github/setup.sh
      - name: Execute the build
        run: |
          export MAVEN_OPTS="$MAVEN_OPTS --add-exports=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED,de.mpg.biochem.mars.fx --add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED,de.mpg.biochem.mars.fx --add-exports=javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED,de.mpg.biochem.mars.fx --add-exports=org.controlsfx.controls/impl.org.controlsfx.skin=ALL-UNNAMED,de.mpg.biochem.mars.fx"
          mvn -B -Djavafx.classifier=linux -Djavadoc.opts="--add-exports javafx.graphics/com.sun.javafx.scene.traversal=de.mpg.biochem.mars.fx --add-exports javafx.controls/com.sun.javafx.scene.control.behavior=de.mpg.biochem.mars.fx --add-exports javafx.controls/com.sun.javafx.scene.control.inputmap=de.mpg.biochem.mars.fx --add-exports org.controlsfx.controls/impl.org.controlsfx.skin=de.mpg.biochem.mars.fx" clean package
          .github/build.sh